(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["components/recommend/index"],{1857:function(t,n,e){"use strict";e.r(n);var o=e("6c52"),i=e("ea82");for(var a in i)["default"].indexOf(a)<0&&function(t){e.d(n,t,(function(){return i[t]}))}(a);e("4f58");var u=e("f0c5"),r=Object(u["a"])(i["default"],o["b"],o["c"],!1,null,"625b709c",null,!1,o["a"],void 0);n["default"]=r.exports},2702:function(t,n,e){},"4f58":function(t,n,e){"use strict";var o=e("2702"),i=e.n(o);i.a},"4f80":function(t,n,e){"use strict";(function(t){Object.defineProperty(n,"__esModule",{value:!0}),n.default=void 0;var o=e("26cb"),i=e("f823"),a=e("041f"),u=(e("ddb3"),e("f26a")),r={components:{WaterfallsFlow:function(){e.e("components/WaterfallsFlow/WaterfallsFlow").then(function(){return resolve(e("7612"))}.bind(null,e)).catch(e.oe)}},computed:(0,o.mapGetters)(["uid"]),props:{hostProduct:{type:Array,default:function(){return[]}},indexP:{type:Boolean,default:!1},isLogin:{type:Boolean,default:!1}},data:function(){return{domain:u.HTTP_REQUEST_URL}},mounted:function(){},onPullDownRefresh:function(){var n=this;setTimeout((function(){var e=n.hostProduct.reverse();n.hostProduct=e,t.stopPullDownRefresh()}),500)},methods:{goDetail:function(n){var e=this;(0,i.goShopDetail)(n,this.uid).then((function(o){e.isLogin?(0,a.initiateAssistApi)(n.activity_id).then((function(n){var e=n.data.product_assist_set_id;t.hideLoading(),t.navigateTo({url:"/pages/activity/assist_detail/index?id="+e})})).catch((function(n){t.showToast({title:n,icon:"none"})})):(e.$emit("isShowAuth",!0),e.$emit("isAuto",!0))}))}}};n.default=r}).call(this,e("543d")["default"])},"6c52":function(t,n,e){"use strict";e.d(n,"b",(function(){return i})),e.d(n,"c",(function(){return a})),e.d(n,"a",(function(){return o}));var o={WaterfallsFlow:function(){return e.e("components/WaterfallsFlow/WaterfallsFlow").then(e.bind(null,"7612"))}},i=function(){var t=this.$createElement;this._self._c},a=[]},ea82:function(t,n,e){"use strict";e.r(n);var o=e("4f80"),i=e.n(o);for(var a in o)["default"].indexOf(a)<0&&function(t){e.d(n,t,(function(){return o[t]}))}(a);n["default"]=i.a}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'components/recommend/index-create-component',
    {
        'components/recommend/index-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('543d')['createComponent'](__webpack_require__("1857"))
        })
    },
    [['components/recommend/index-create-component']]
]);
