(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["components/orderGoods/index"],{1667:function(t,e,a){"use strict";a.d(e,"b",(function(){return n})),a.d(e,"c",(function(){return r})),a.d(e,"a",(function(){}));var n=function(){var t=this.$createElement;this._self._c},r=[]},"33f6":function(t,e,a){},"744d":function(t,e,a){"use strict";a.r(e);var n=a("b376"),r=a.n(n);for(var i in n)["default"].indexOf(i)<0&&function(t){a.d(e,t,(function(){return n[t]}))}(i);e["default"]=r.a},b376:function(t,e,a){"use strict";(function(t){Object.defineProperty(e,"__esModule",{value:!0}),e.default=void 0;var n=a("4d59"),r=a("f823"),i=a("041f"),o=a("26cb"),d={props:{evaluate:{type:Number,default:0},activityType:{type:Number,default:0},cartInfo:{type:Array,default:function(){return[]}},orderId:{type:String,default:""},jump:{type:Boolean,default:!1},orderData:{type:Object,default:function(){return{}}}},computed:(0,o.mapGetters)(["viewColor"]),data:function(){return{totalNmu:"",isTimePay:!1}},watch:{cartInfo:function(t,e){var a=0;t.forEach((function(t,e){a+=t.cart_num})),this.totalNmu=a}},onShow:function(){this.isPayBalance()},mounted:function(){},methods:{evaluateTap:function(e,a){t.navigateTo({url:"/pages/users/goods_comment_con/index?uni=".concat(e,"&order_id=").concat(a)})},isPayBalance:function(){10===this.orderData.status&&(new Date<new Date(this.orderData.presellOrder.final_start_time)?this.isTimePay=!1:new Date>=new Date(this.orderData.presellOrder.final_start_time)&&new Date<=new Date(this.orderData.presellOrder.final_start_time)&&(this.isTimePay=!0))},jumpCon:function(e){4==e.product_type&&(e.activity_id=e.cart_info&&e.cart_info.activeSku.product_group_id),3==e.product_type&&(e.activity_id=e.cart_info&&e.cart_info.productAssistAttr.product_assist_id),(0,r.goShopDetail)(e).then((function(a){(0,i.initiateAssistApi)(e.activity_id).then((function(e){var a=e.data.product_assist_set_id;t.hideLoading(),t.navigateTo({url:"/pages/activity/assist_detail/index?id="+a})})).catch((function(e){t.showToast({title:e,icon:"none"})}))}))},refund:function(e){var a=this;(0,n.openOrderRefundSubscribe)().then((function(){t.hideLoading(),0==a.evaluate||9==a.evaluate||0!=a.orderData.is_virtual?t.navigateTo({url:"/pages/users/refund/confirm?order_id="+a.orderId+"&type=1&ids="+e.order_product_id+"&refund_type=1&order_type="+a.orderData.order_type}):t.navigateTo({url:"/pages/users/refund/select?order_id="+a.orderId+"&type=1&order_type="+a.orderData.order_type+"&ids="+e.order_product_id})})).catch((function(){t.hideLoading()}))}}};e.default=d}).call(this,a("543d")["default"])},b8dd:function(t,e,a){"use strict";var n=a("33f6"),r=a.n(n);r.a},d49b:function(t,e,a){"use strict";a.r(e);var n=a("1667"),r=a("744d");for(var i in r)["default"].indexOf(i)<0&&function(t){a.d(e,t,(function(){return r[t]}))}(i);a("b8dd");var o=a("f0c5"),d=Object(o["a"])(r["default"],n["b"],n["c"],!1,null,"4149525d",null,!1,n["a"],void 0);e["default"]=d.exports}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'components/orderGoods/index-create-component',
    {
        'components/orderGoods/index-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('543d')['createComponent'](__webpack_require__("d49b"))
        })
    },
    [['components/orderGoods/index-create-component']]
]);
