(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["components/guide/index"],{"032c":function(t,e,n){"use strict";var a=n("d0dc"),i=n.n(a);i.a},"06fc":function(t,e,n){"use strict";(function(t){Object.defineProperty(e,"__esModule",{value:!0}),e.default=void 0;var n=getApp(),a={data:function(){return{autoplay:!0,circular:!0,duration:500,interval:2500,jumpover:"跳过",experience:"立即体验",time:this.advData.config.open_screen_time,timecount:void 0,navH:0}},props:{advData:{type:Object,default:function(){}},closeType:{type:Number,default:1}},mounted:function(){this.timer(),this.navH=n.globalData.navHeight},methods:{stopChange:function(){if(1==this.advData.list.length)return!1},timer:function(){var t=this,e=this.advData.config.open_screen_time||5;this.timecount=setInterval((function(){e--,t.time=e,e<=0&&(clearInterval(t.timecount),t.launchFlag())}),1e3)},launchFlag:function(){clearInterval(this.timecount),t.switchTab({url:"/pages/index/index"})},jump:function(e){e&&(clearInterval(this.timecount),-1!=e.indexOf("http")?t.navigateTo({url:"/pages/annex/web_view/index?url=".concat(e)}):-1==["/pages/goods_cate/goods_cate","/pages/order_addcart/order_addcart","/pages/user/index","/pages/index/index","/pages/plant_grass/index"].indexOf(e)?t.navigateTo({url:e}):t.reLaunch({url:e}))}}};e.default=a}).call(this,n("543d")["default"])},"18ac":function(t,e,n){"use strict";n.r(e);var a=n("06fc"),i=n.n(a);for(var c in a)["default"].indexOf(c)<0&&function(t){n.d(e,t,(function(){return a[t]}))}(c);e["default"]=i.a},"3d80":function(t,e,n){"use strict";n.r(e);var a=n("451b"),i=n("18ac");for(var c in i)["default"].indexOf(c)<0&&function(t){n.d(e,t,(function(){return i[t]}))}(c);n("032c");var u=n("f0c5"),r=Object(u["a"])(i["default"],a["b"],a["c"],!1,null,"6d796162",null,!1,a["a"],void 0);e["default"]=r.exports},"451b":function(t,e,n){"use strict";n.d(e,"b",(function(){return a})),n.d(e,"c",(function(){return i})),n.d(e,"a",(function(){}));var a=function(){var t=this.$createElement,e=(this._self._c,this.advData.list.length),n=e?this.advData.list.length:null;this.$mp.data=Object.assign({},{$root:{g0:e,g1:n}})},i=[]},d0dc:function(t,e,n){}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'components/guide/index-create-component',
    {
        'components/guide/index-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('543d')['createComponent'](__webpack_require__("3d80"))
        })
    },
    [['components/guide/index-create-component']]
]);
