(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["components/mentioned"],{"544c":function(t,e,i){"use strict";i.d(e,"b",(function(){return n})),i.d(e,"c",(function(){return c})),i.d(e,"a",(function(){}));var n=function(){var t=this.$createElement;this._self._c},c=[]},"94b6":function(t,e,i){"use strict";i.r(e);var n=i("544c"),c=i("c8e2");for(var o in c)["default"].indexOf(o)<0&&function(t){i.d(e,t,(function(){return c[t]}))}(o);i("a331");var a=i("f0c5"),r=Object(a["a"])(c["default"],n["b"],n["c"],!1,null,"2810ba13",null,!1,n["a"],void 0);e["default"]=r.exports},a331:function(t,e,i){"use strict";var n=i("c149"),c=i.n(n);c.a},c149:function(t,e,i){},c8e2:function(t,e,i){"use strict";i.r(e);var n=i("f4c0"),c=i.n(n);for(var o in n)["default"].indexOf(o)<0&&function(t){i.d(e,t,(function(){return n[t]}))}(o);e["default"]=c.a},f4c0:function(t,e,i){"use strict";(function(t){var n=i("4ea4");Object.defineProperty(e,"__esModule",{value:!0}),e.default=void 0;var c=n(i("9523")),o=(i("f823"),i("26cb"));function a(t,e){var i=Object.keys(t);if(Object.getOwnPropertySymbols){var n=Object.getOwnPropertySymbols(t);e&&(n=n.filter((function(e){return Object.getOwnPropertyDescriptor(t,e).enumerable}))),i.push.apply(i,n)}return i}var r={computed:function(t){for(var e=1;e<arguments.length;e++){var i=null!=arguments[e]?arguments[e]:{};e%2?a(Object(i),!0).forEach((function(e){(0,c.default)(t,e,i[e])})):Object.getOwnPropertyDescriptors?Object.defineProperties(t,Object.getOwnPropertyDescriptors(i)):a(Object(i)).forEach((function(e){Object.defineProperty(t,e,Object.getOwnPropertyDescriptor(i,e))}))}return t}({},(0,o.mapGetters)(["viewColor"])),props:{list:{type:Array,default:[]},uid:{type:Number},isHome:{type:Boolean,default:!1}},data:function(){return{popup:{show:!1}}},methods:{closePopup:function(){this.$set(this.popup,"show",!1)},showPopup:function(){this.$set(this.popup,"show",!0)},goDetail:function(e){1===e.product_type?t.navigateTo({url:"/pages/activity/goods_seckill_details/index?id=".concat(e.product_id,"&time=").concat(e.stop_time,"&spid=").concat(this.uid)}):2===e.product_type?t.navigateTo({url:"/pages/activity/presell_details/index?id=".concat(e.activity_id,"&spid=").concat(this.uid)}):0===e.product_type?t.navigateTo({url:"/pages/goods_details/index?id=".concat(e.product_id,"&spid=").concat(this.uid)}):4===e.product_type?t.navigateTo({url:"/pages/activity/combination_details/index?id=".concat(e.activity_id,"&spid=").concat(this.uid)}):40===e.product_type&&t.navigateTo({url:"/pages/activity/combination_status/index?id=".concat(e.activity_id,"&spid=").concat(this.uid)})}}};e.default=r}).call(this,i("543d")["default"])}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'components/mentioned-create-component',
    {
        'components/mentioned-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('543d')['createComponent'](__webpack_require__("94b6"))
        })
    },
    [['components/mentioned-create-component']]
]);
