(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["pages/index/component/combination"],{"14da":function(t,n,i){"use strict";i.r(n);var o=i("ad0b"),a=i("553f");for(var e in a)["default"].indexOf(e)<0&&function(t){i.d(n,t,(function(){return a[t]}))}(e);i("ac98");var l=i("f0c5"),d=Object(l["a"])(a["default"],o["b"],o["c"],!1,null,null,null,!1,o["a"],void 0);n["default"]=d.exports},"4b13":function(t,n,i){"use strict";Object.defineProperty(n,"__esModule",{value:!0}),n.default=void 0;var o=i("f26a"),a=i("58d4"),e={name:"combination",props:{dataConfig:{type:Object,default:function(){}},merId:{type:String||Number,default:""}},data:function(){return{domain:o.HTTP_REQUEST_URL,combinationList:[],themeColor:this.dataConfig.themeColor.color[0].item,styleType:this.dataConfig.tabConfig.tabVal,mbConfig:2*this.dataConfig.mbConfig.val,bgStyle:this.dataConfig.bgStyle.type?20:0,bgColor:this.dataConfig.bgColor.color[0].item,txtColor:this.dataConfig.txtColor.color[0].item,conStyle:this.dataConfig.conStyle.type,priceShow:this.dataConfig.priceShow.val,bntShow:this.dataConfig.bntShow.val,titleShow:this.dataConfig.titleShow.val,pinkShow:this.dataConfig.pinkShow.val,diy_id:this.dataConfig.did,unique:this.dataConfig.timestamp}},created:function(){},mounted:function(){this.getCombinationList()},methods:{getCombinationList:function(){var t=this;(0,a.getCombinationData)({diy_id:t.diy_id,unique:t.unique,mer_id:t.merId,page:1,limit:2==t.styleType?3:12}).then((function(n){t.combinationList=n.data.list}))}}};n.default=e},"553f":function(t,n,i){"use strict";i.r(n);var o=i("4b13"),a=i.n(o);for(var e in o)["default"].indexOf(e)<0&&function(t){i.d(n,t,(function(){return o[t]}))}(e);n["default"]=a.a},ac98:function(t,n,i){"use strict";var o=i("b145"),a=i.n(o);a.a},ad0b:function(t,n,i){"use strict";i.d(n,"b",(function(){return a})),i.d(n,"c",(function(){return e})),i.d(n,"a",(function(){return o}));var o={easyLoadimage:function(){return Promise.all([i.e("common/vendor"),i.e("components/easy-loadimage/easy-loadimage")]).then(i.bind(null,"2243"))}},a=function(){var t=this,n=t.$createElement,i=(t._self._c,t.combinationList.length),o=i>0&&2==t.styleType?t.combinationList.length:null,a=i>0&&2==t.styleType?t.combinationList.length:null,e=i>0&&2==t.styleType?t.combinationList.length:null;t.$mp.data=Object.assign({},{$root:{g0:i,g1:o,g2:a,g3:e}})},e=[]},b145:function(t,n,i){}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'pages/index/component/combination-create-component',
    {
        'pages/index/component/combination-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('543d')['createComponent'](__webpack_require__("14da"))
        })
    },
    [['pages/index/component/combination-create-component']]
]);
