(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["pages/index/component/shopList"],{1492:function(t,n,i){"use strict";i.r(n);var o=i("67b4"),e=i("42f9");for(var a in e)["default"].indexOf(a)<0&&function(t){i.d(n,t,(function(){return e[t]}))}(a);i("9ef0");var r=i("f0c5"),s=Object(r["a"])(e["default"],o["b"],o["c"],!1,null,"24b722c4",null,!1,o["a"],void 0);n["default"]=s.exports},"2d7c":function(t,n,i){},"36a0":function(t,n,i){"use strict";(function(t){Object.defineProperty(n,"__esModule",{value:!0}),n.default=void 0;var o=i("58d4"),e=(i("26cb"),i("3255")),a={computed:(0,e.configMap)(["hide_mer_status"]),components:{easyLoadimage:function(){Promise.all([i.e("common/vendor"),i.e("components/easy-loadimage/easy-loadimage")]).then(function(){return resolve(i("2243"))}.bind(null,i)).catch(i.oe)}},props:{dataConfig:{type:Object,default:function(){}}},data:function(){return{brandList:[],mbConfig:2*this.dataConfig.mbConfig.val,prConfig:2*this.dataConfig.prConfig.val,logoUrl:this.dataConfig.logoConfig.url,bgStyle:this.dataConfig.bgStyle.type?"16":0,bgColor:this.dataConfig.bgColor.color[0].item,themeColor:this.dataConfig.themeColor.color[0].item,tabConfig:this.dataConfig.tabConfig.tabVal,numConfig:this.dataConfig.numConfig.val,titleShow:this.dataConfig.titleShow.val,priceShow:this.dataConfig.priceShow.val,diy_id:this.dataConfig.did,unique:this.dataConfig.timestamp}},created:function(){},mounted:function(){this.storeMerchant()},methods:{goStore:function(n){1!=this.hide_mer_status&&t.navigateTo({url:"/pages/store/home/index?id=".concat(n)})},moreShop:function(){t.navigateTo({url:"/pages/store/shopStreet/index?cate_id=&type_id="})},storeMerchant:function(){var t=this;(0,o.storeList)({diy_id:this.diy_id,unique:this.unique,page:1,limit:this.numConfig?this.numConfig:4,is_best:1}).then((function(n){t.brandList=n.data.list}))}}};n.default=a}).call(this,i("543d")["default"])},"42f9":function(t,n,i){"use strict";i.r(n);var o=i("36a0"),e=i.n(o);for(var a in o)["default"].indexOf(a)<0&&function(t){i.d(n,t,(function(){return o[t]}))}(a);n["default"]=e.a},"67b4":function(t,n,i){"use strict";i.d(n,"b",(function(){return e})),i.d(n,"c",(function(){return a})),i.d(n,"a",(function(){return o}));var o={easyLoadimage:function(){return Promise.all([i.e("common/vendor"),i.e("components/easy-loadimage/easy-loadimage")]).then(i.bind(null,"2243"))}},e=function(){var t=this,n=t.$createElement,i=(t._self._c,0==t.tabConfig?t.__map(t.brandList,(function(n,i){var o=t.__get_orig(n),e=n.all_recommend.length;return{$orig:o,g0:e}})):null);t.$mp.data=Object.assign({},{$root:{l0:i}})},a=[]},"9ef0":function(t,n,i){"use strict";var o=i("2d7c"),e=i.n(o);e.a}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'pages/index/component/shopList-create-component',
    {
        'pages/index/component/shopList-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('543d')['createComponent'](__webpack_require__("1492"))
        })
    },
    [['pages/index/component/shopList-create-component']]
]);
