(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["pages/index/component/swiperBg"],{2037:function(t,i,n){"use strict";n.d(i,"b",(function(){return a})),n.d(i,"c",(function(){return e})),n.d(i,"a",(function(){}));var a=function(){var t=this.$createElement,i=(this._self._c,0!=this.swiperType?this.imgUrls.length:null);this.$mp.data=Object.assign({},{$root:{g0:i}})},e=[]},"3a48":function(t,i,n){"use strict";var a=n("ad8c"),e=n.n(a);e.a},"9a0d":function(t,i,n){"use strict";n.r(i);var a=n("2037"),e=n("a3e7");for(var o in e)["default"].indexOf(o)<0&&function(t){n.d(i,t,(function(){return e[t]}))}(o);n("3a48");var r=n("f0c5"),s=Object(r["a"])(e["default"],a["b"],a["c"],!1,null,"c4118e32",null,!1,a["a"],void 0);i["default"]=s.exports},a3e7:function(t,i,n){"use strict";n.r(i);var a=n("e91a"),e=n.n(a);for(var o in a)["default"].indexOf(o)<0&&function(t){n.d(i,t,(function(){return a[t]}))}(o);i["default"]=e.a},ad8c:function(t,i,n){},e91a:function(t,i,n){"use strict";(function(t){Object.defineProperty(i,"__esModule",{value:!0}),i.default=void 0;var a=n("3255"),e={name:"swiperBg",props:{dataConfig:{type:Object,default:function(){}},merId:{}},data:function(){return{indicatorDots:!1,circular:!0,autoplay:!0,interval:3e3,duration:500,imgUrls:[],bgColor0:this.dataConfig.isShow.val?this.dataConfig.bgColor.color[0].item:"transparent",bgColor1:this.dataConfig.isShow.val?this.dataConfig.bgColor.color[1].item:"transparent",marginTop:2*this.dataConfig.mbConfig.val,paddinglr:2*this.dataConfig.lrConfig.val,docConfig:this.dataConfig.docConfig.type,imgConfig:this.dataConfig.imgConfig.type,txtStyle:this.dataConfig.txtStyle.type,imageH:310,swiperCur:0,swiperType:1}},watch:{imageH:function(t,i){this.imageH=t}},created:function(){this.imgUrls=this.dataConfig.swiperConfig.list},mounted:function(){var i=this;i.$nextTick((function(){t.getImageInfo({src:i.setDomain(i.imgUrls[0].img),success:function(t){if(t&&t.height>0){var n=t.height*(730/t.width);i.$set(i,"imageH",n)}else i.$set(i,"imageH",375)},fail:function(t){i.$set(i,"imageH",375)}})}))},methods:{setDomain:function(t){return t=t?t.toString():"",t.indexOf("https://")>-1?t:t.replace("http://","https://")},swiperChange:function(t){var i=t.detail,n=(i.current,i.source);"autoplay"!==n&&"touch"!==n||(this.swiperCur=t.detail.current)},goDetail:function(t){var i=t.info[1].value;i=(0,a.merPath)(i,this.merId),this.$util.JumpPath(i)}}};i.default=e}).call(this,n("543d")["default"])}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'pages/index/component/swiperBg-create-component',
    {
        'pages/index/component/swiperBg-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('543d')['createComponent'](__webpack_require__("9a0d"))
        })
    },
    [['pages/index/component/swiperBg-create-component']]
]);
