(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["pages/index/component/topic"],{"1d3d":function(t,i,n){},"4ff6":function(t,i,n){"use strict";n.d(i,"b",(function(){return o})),n.d(i,"c",(function(){return a})),n.d(i,"a",(function(){}));var o=function(){var t=this.$createElement,i=(this._self._c,this.activityData.length),n=i>0?this.activityData.length:null,o=i>0&&n?this.activityData.length:null;this.$mp.data=Object.assign({},{$root:{g0:i,g1:n,g2:o}})},a=[]},"6aef":function(t,i,n){"use strict";Object.defineProperty(i,"__esModule",{value:!0}),i.default=void 0;var o=n("f26a"),a=n("3255"),e={name:"topic",props:{dataConfig:{type:Object,default:function(){}},merId:{type:String||Number,default:""}},data:function(){return{indicatorDots:!1,autoplay:!0,duration:500,activityData:this.dataConfig.menuConfig.list,bgColor:this.dataConfig.colorShow.val?this.dataConfig.bgColor.color[0].item:"transparent",pointerColor:this.dataConfig.pointerColor&&this.dataConfig.pointerColor.color&&this.dataConfig.pointerColor.color[0].item||"#ffffff",mbConfig:2*this.dataConfig.mbConfig.val,prConfig:2*this.dataConfig.prConfig.val,txtStyle:this.dataConfig.txtStyle.type,bgStyle:this.dataConfig.bgStyle.type?20:0,colorShow:this.dataConfig.colorShow.val,pointerStyle:this.dataConfig.pointerStyle.type,conStyle:this.dataConfig.conStyle.type,domain:o.HTTP_REQUEST_URL}},created:function(){},mounted:function(){},methods:{goTopicDetail:function(t){var i=t;i=(0,a.merPath)(i,this.merId),this.$util.JumpPath(i)}}};i.default=e},"9fcb":function(t,i,n){"use strict";n.r(i);var o=n("6aef"),a=n.n(o);for(var e in o)["default"].indexOf(e)<0&&function(t){n.d(i,t,(function(){return o[t]}))}(e);i["default"]=a.a},b890:function(t,i,n){"use strict";n.r(i);var o=n("4ff6"),a=n("9fcb");for(var e in a)["default"].indexOf(e)<0&&function(t){n.d(i,t,(function(){return a[t]}))}(e);n("e49c");var f=n("f0c5"),r=Object(f["a"])(a["default"],o["b"],o["c"],!1,null,"603cfa30",null,!1,o["a"],void 0);i["default"]=r.exports},e49c:function(t,i,n){"use strict";var o=n("1d3d"),a=n.n(o);a.a}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'pages/index/component/topic-create-component',
    {
        'pages/index/component/topic-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('543d')['createComponent'](__webpack_require__("b890"))
        })
    },
    [['pages/index/component/topic-create-component']]
]);
