(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["components/passwordPopup/index"],{"0093":function(t,n,i){"use strict";i.r(n);var o=i("cf68"),e=i.n(o);for(var a in o)["default"].indexOf(a)<0&&function(t){i.d(n,t,(function(){return o[t]}))}(a);n["default"]=e.a},"1a5a":function(t,n,i){},4117:function(t,n,i){"use strict";i.d(n,"b",(function(){return o})),i.d(n,"c",(function(){return e})),i.d(n,"a",(function(){}));var o=function(){var t=this.$createElement;this._self._c},e=[]},"5edd":function(t,n,i){"use strict";i.r(n);var o=i("4117"),e=i("0093");for(var a in e)["default"].indexOf(a)<0&&function(t){i.d(n,t,(function(){return e[t]}))}(a);i("a359");var d=i("f0c5"),u=Object(d["a"])(e["default"],o["b"],o["c"],!1,null,"1368eabe",null,!1,o["a"],void 0);n["default"]=u.exports},a359:function(t,n,i){"use strict";var o=i("1a5a"),e=i.n(o);e.a},cf68:function(t,n,i){"use strict";(function(t){Object.defineProperty(n,"__esModule",{value:!0}),n.default=void 0;var o=i("6859"),e=i("26cb"),a=(i("ddb3"),i("f823")),d=i("041f"),u=i("f26a"),c={props:{isLogin:{type:Boolean,default:!1}},data:function(){return{window:!1,couponList:[],userInfo:{},storeInfo:{},pwdInfo:{},domain:u.HTTP_REQUEST_URL}},computed:(0,e.mapGetters)(["copyPwd","uid"]),watch:{copyPwd:{handler:function(t,n){t&&this.resolution(t)},immediate:!0,deep:!0}},mounted:function(){},beforeDestroy:function(){},methods:{close:function(){this.window=!1},resolution:function(n){var i=this,e=t.getStorageSync("pwdKey");(0,o.pwdResolution)(n).then((function(n){n.data.user&&n.data.user.uid!=i.uid&&e!=n.data.com&&(i.window=!0,i.pwdInfo=n.data,i.userInfo=n.data.user,i.storeInfo=n.data.data,n.data.activity_id&&(i.storeInfo.activity_id=n.data.activity_id),n.data.product_type&&(i.storeInfo.product_type=n.data.product_type),i.$store.commit("PARSE_PWD",null),t.setStorageSync("pwdKey",n.data.com))}))},goDetail:function(n){var i=this;(0,a.goShopDetail)(n,this.uid).then((function(o){i.$store.commit("PARSE_PWD",null),i.isLogin?(0,d.initiateAssistApi)(n.activity_id).then((function(n){var i=n.data.product_assist_set_id;t.hideLoading(),t.navigateTo({url:"/pages/activity/assist_detail/index?id="+i})})).catch((function(n){t.showToast({title:n,icon:"none"})})):(i.$emit("isShowAuth",!0),i.$emit("isAuto",!0))}))}}};n.default=c}).call(this,i("543d")["default"])}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'components/passwordPopup/index-create-component',
    {
        'components/passwordPopup/index-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('543d')['createComponent'](__webpack_require__("5edd"))
        })
    },
    [['components/passwordPopup/index-create-component']]
]);
