(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["pages/product/components/selectForm"],{"40cb":function(t,e,n){"use strict";Object.defineProperty(e,"__esModule",{value:!0}),e.default=void 0;var i={props:{platformClassification:{type:Array,default:function(){return[]}},form:{type:Object,default:function(){return{}}}},data:function(){return{value:"",formData:this.form}},watch:{formData:{handler:function(t){this.$emit("input",t)},deep:!0},form:{handler:function(t){this.formData=t},deep:!0}},created:function(){var t=this;this.platformClassification.forEach((function(e){e.inforValue&&t.$emit("formInitData",e.inforValue,e.model)}))},methods:{selectItem:function(t){t.jumpLogic?this.$emit("handleJumpLogic",t):this.$emit("handleSelectItem",t)},radioChange:function(t,e){this.$emit("radioChange",t.detail.value,e)},switchChange:function(t,e){this.$emit("switchChange",t.detail.value,e)},selectRadio:function(t){t.select=!t.select},checkChange:function(t,e){this.$emit("checkChange",t.detail.value,e)}}};e.default=i},"50b2":function(t,e,n){"use strict";n.r(e);var i=n("5f78"),a=n("f1df");for(var o in a)["default"].indexOf(o)<0&&function(t){n.d(e,t,(function(){return a[t]}))}(o);n("e518");var c=n("f0c5"),f=Object(c["a"])(a["default"],i["b"],i["c"],!1,null,"6f693e01",null,!1,i["a"],void 0);e["default"]=f.exports},"5f78":function(t,e,n){"use strict";n.d(e,"b",(function(){return i})),n.d(e,"c",(function(){return a})),n.d(e,"a",(function(){}));var i=function(){var t=this,e=t.$createElement,n=(t._self._c,t.__map(t.platformClassification,(function(e,n){var i=t.__get_orig(e),a=e.DoNotShow||"select"!=e.type&&"input"!=e.type&&"switch"!=e.type?null:Object.keys(e).indexOf("select");return{$orig:i,g0:a}})));t.$mp.data=Object.assign({},{$root:{l0:n}})},a=[]},"7b49":function(t,e,n){},e518:function(t,e,n){"use strict";var i=n("7b49"),a=n.n(i);a.a},f1df:function(t,e,n){"use strict";n.r(e);var i=n("40cb"),a=n.n(i);for(var o in i)["default"].indexOf(o)<0&&function(t){n.d(e,t,(function(){return i[t]}))}(o);e["default"]=a.a}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'pages/product/components/selectForm-create-component',
    {
        'pages/product/components/selectForm-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('543d')['createComponent'](__webpack_require__("50b2"))
        })
    },
    [['pages/product/components/selectForm-create-component']]
]);
