(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["pages/product/components/specificationAttr"],{"1b8d":function(t,e,a){"use strict";a.d(e,"b",(function(){return n})),a.d(e,"c",(function(){return i})),a.d(e,"a",(function(){}));var n=function(){var t=this.$createElement,e=(this._self._c,this.specData.name?this.specData.name.length:null);this.$mp.data=Object.assign({},{$root:{g0:e}})},i=[]},"36af":function(t,e,a){"use strict";var n=a("9b0f"),i=a.n(n);i.a},"39b1":function(t,e,a){"use strict";Object.defineProperty(e,"__esModule",{value:!0}),e.default=void 0;var n={props:{specData:{type:Object,default:function(){return{showpopup:!1,name:"",detail:""}}}},data:function(){return{specification:[],name:this.names,detail:this.details,loading:!1}},watch:{},onLoad:function(t){},onShow:function(){},methods:{close:function(){this.$emit("changeClose")},resetData:function(){this.$set(this.specData,"name",""),this.$set(this.specData,"detail","")},save:function(){if(!this.specData.name)return this.$util.Tips({title:"请输入规格名称"});if(!this.specData.detail)return this.$util.Tips({title:"请输入规格属性"});var t=this.specData.detail.split(/[(\r\n)\r\n]+/);this.loading=!0,t.forEach((function(e,a){e||t.splice(a,1)})),this.$emit("getData",{value:this.specData.name,detail:t}),this.loading=!1}}};e.default=n},"5140e":function(t,e,a){"use strict";a.r(e);var n=a("1b8d"),i=a("a36d");for(var s in i)["default"].indexOf(s)<0&&function(t){a.d(e,t,(function(){return i[t]}))}(s);a("36af");var c=a("f0c5"),o=Object(c["a"])(i["default"],n["b"],n["c"],!1,null,"50fa6e20",null,!1,n["a"],void 0);e["default"]=o.exports},"9b0f":function(t,e,a){},a36d:function(t,e,a){"use strict";a.r(e);var n=a("39b1"),i=a.n(n);for(var s in n)["default"].indexOf(s)<0&&function(t){a.d(e,t,(function(){return n[t]}))}(s);e["default"]=i.a}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'pages/product/components/specificationAttr-create-component',
    {
        'pages/product/components/specificationAttr-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('543d')['createComponent'](__webpack_require__("5140e"))
        })
    },
    [['pages/product/components/specificationAttr-create-component']]
]);
