(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["pages/index/component/coupon"],{"21ef":function(t,n,i){},"3ffe":function(t,n,i){"use strict";(function(t){Object.defineProperty(n,"__esModule",{value:!0}),n.default=void 0;var o=i("58d4"),e=i("f26a"),a=i("ddb3"),u=i("26cb"),f={name:"coupon",props:{dataConfig:{type:Object,default:function(){}},merId:{type:String||Number,default:""}},computed:(0,u.mapGetters)(["isLogin"]),components:{},watch:{isLogin:{handler:function(t,n){t&&this.getCoupon()},deep:!0}},data:function(){return{domain:e.HTTP_REQUEST_URL,couponList:[],style:this.dataConfig.tabConfig&&this.dataConfig.tabConfig.tabVal||0,themeColor:this.dataConfig.themeColor.color[0].item,mbConfig:2*this.dataConfig.mbConfig.val,prConfig:this.dataConfig.prConfig&&2*this.dataConfig.prConfig.val,bgStyle:this.dataConfig.bgStyle.type?20:0,diy_id:this.dataConfig.did,unique:this.dataConfig.timestamp}},created:function(){},mounted:function(){this.getCoupon()},methods:{getCoupon:function(){var t=this;(0,o.getCouponData)({diy_id:t.diy_id,unique:t.unique,mer_id:t.merId,page:1,limit:10}).then((function(n){t.$set(t,"couponList",n.data.list)})).catch((function(n){return t.$util.Tips({title:n})}))},receiveCoupon:function(n){!1===this.isLogin?(0,a.toLogin)():(0,o.setCouponReceive)(n.coupon_id).then((function(i){n.issue=1,t.showToast({title:i.message,icon:"none"})})).catch((function(n){t.showToast({title:n,icon:"none"})}))}}};n.default=f}).call(this,i("543d")["default"])},a32d:function(t,n,i){"use strict";i.r(n);var o=i("3ffe"),e=i.n(o);for(var a in o)["default"].indexOf(a)<0&&function(t){i.d(n,t,(function(){return o[t]}))}(a);n["default"]=e.a},ac25:function(t,n,i){"use strict";i.r(n);var o=i("c8d4"),e=i("a32d");for(var a in e)["default"].indexOf(a)<0&&function(t){i.d(n,t,(function(){return e[t]}))}(a);i("f8e1");var u=i("f0c5"),f=Object(u["a"])(e["default"],o["b"],o["c"],!1,null,"ea9757da",null,!1,o["a"],void 0);n["default"]=f.exports},c8d4:function(t,n,i){"use strict";i.d(n,"b",(function(){return o})),i.d(n,"c",(function(){return e})),i.d(n,"a",(function(){}));var o=function(){var t=this.$createElement,n=(this._self._c,this.couponList.length);this.$mp.data=Object.assign({},{$root:{g0:n}})},e=[]},f8e1:function(t,n,i){"use strict";var o=i("21ef"),e=i.n(o);e.a}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'pages/index/component/coupon-create-component',
    {
        'pages/index/component/coupon-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('543d')['createComponent'](__webpack_require__("ac25"))
        })
    },
    [['pages/index/component/coupon-create-component']]
]);
