(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["pages/index/component/goodList"],{"098e":function(t,i,e){"use strict";e.r(i);var n=e("90e4"),o=e.n(n);for(var a in n)["default"].indexOf(a)<0&&function(t){e.d(i,t,(function(){return n[t]}))}(a);i["default"]=o.a},"7b84":function(t,i,e){"use strict";e.r(i);var n=e("a7de"),o=e("098e");for(var a in o)["default"].indexOf(a)<0&&function(t){e.d(i,t,(function(){return o[t]}))}(a);e("d3f4");var d=e("f0c5"),r=Object(d["a"])(o["default"],n["b"],n["c"],!1,null,"71a43fb4",null,!1,n["a"],void 0);i["default"]=r.exports},"90e4":function(t,i,e){"use strict";Object.defineProperty(i,"__esModule",{value:!0}),i.default=void 0;var n=e("58d4"),o={name:"goodList",props:{dataConfig:{type:Object,default:function(){}},merId:{type:String||Number,default:""}},data:function(){return{tempArr:[],mbConfig:2*this.dataConfig.mbConfig.val,numConfig:(this.dataConfig.numConfig.val,this.dataConfig.numConfig.val),themeColor:this.dataConfig.themeColor.color[0].item,priceColor:this.dataConfig.fontColor.color[0].item,labelColor:this.dataConfig.labelColor.color[0].item,itemStyle:this.dataConfig.itemStyle.type,sortType:this.dataConfig.goodsSort.type,conStyle:this.dataConfig.conStyle.type,bgStyle:this.dataConfig.bgStyle.type?"20":"0",type:this.dataConfig.tabConfig.tabVal||0,selectId:this.dataConfig.selectConfig.activeValue||0,productIds:this.dataConfig.goodsList.ids||[],titleShow:this.dataConfig.titleShow.val,priceShow:this.dataConfig.priceShow.val,couponShow:this.dataConfig.couponShow.val,diy_id:this.dataConfig.did,unique:this.dataConfig.timestamp}},created:function(){},mounted:function(){this.productslist()},methods:{productslist:function(){var t=this,i={};1==this.type?i={diy_id:this.diy_id,unique:this.unique,mer_id:this.merId,product_ids:this.productIds.toString(),limit:this.productIds.length}:(i={diy_id:this.diy_id,unique:this.unique,mer_id:this.merId,order:2==this.sortType?"price_asc":1==this.sortType?"sales":"",limit:this.numConfig},this.merId?i.mer_cate_id=this.selectId.toString():i.cate_pid=this.selectId.toString()),(0,n.getProductData)(i).then((function(i){t.tempArr=i.data.list}))},goDetail:function(t){this.$emit("detail",t)}}};i.default=o},"91b2":function(t,i,e){},a7de:function(t,i,e){"use strict";e.d(i,"b",(function(){return o})),e.d(i,"c",(function(){return a})),e.d(i,"a",(function(){return n}));var n={easyLoadimage:function(){return Promise.all([e.e("common/vendor"),e.e("components/easy-loadimage/easy-loadimage")]).then(e.bind(null,"2243"))}},o=function(){var t=this,i=t.$createElement,e=(t._self._c,t.tempArr.length),n=e&&0==t.itemStyle?t.tempArr.length:null,o=e&&1==t.itemStyle?t.tempArr.length:null,a=e&&2==t.itemStyle?t.tempArr.length:null,d=e&&3==t.itemStyle?t.tempArr.length:null;t.$mp.data=Object.assign({},{$root:{g0:e,g1:n,g2:o,g3:a,g4:d}})},a=[]},d3f4:function(t,i,e){"use strict";var n=e("91b2"),o=e.n(n);o.a}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'pages/index/component/goodList-create-component',
    {
        'pages/index/component/goodList-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('543d')['createComponent'](__webpack_require__("7b84"))
        })
    },
    [['pages/index/component/goodList-create-component']]
]);
