(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["components/privacyAgreementPopup/index"],{"142d":function(e,t,n){"use strict";n.d(t,"b",(function(){return r})),n.d(t,"c",(function(){return c})),n.d(t,"a",(function(){}));var r=function(){var e=this.$createElement;this._self._c},c=[]},"2fed":function(e,t,n){},"7a9b":function(e,t,n){"use strict";n.r(t);var r=n("142d"),c=n("c2fa");for(var i in c)["default"].indexOf(i)<0&&function(e){n.d(t,e,(function(){return c[e]}))}(i);n("ed0c"),n("9aec");var o=n("f0c5"),a=Object(o["a"])(c["default"],r["b"],r["c"],!1,null,"61665209",null,!1,r["a"],void 0);t["default"]=a.exports},9544:function(e,t,n){"use strict";(function(e,r){var c=n("4ea4");Object.defineProperty(t,"__esModule",{value:!0}),t.default=void 0;var i=c(n("9523")),o=n("26cb"),a=n("3255");c(n("823f"));function u(e,t){var n=Object.keys(e);if(Object.getOwnPropertySymbols){var r=Object.getOwnPropertySymbols(e);t&&(r=r.filter((function(t){return Object.getOwnPropertyDescriptor(e,t).enumerable}))),n.push.apply(n,r)}return n}getApp();var f={data:function(){return{isShow:!1,agreementName:"",mpData:e.getStorageSync("copyRight")}},computed:function(e){for(var t=1;t<arguments.length;t++){var n=null!=arguments[t]?arguments[t]:{};t%2?u(Object(n),!0).forEach((function(t){(0,i.default)(e,t,n[t])})):Object.getOwnPropertyDescriptors?Object.defineProperties(e,Object.getOwnPropertyDescriptors(n)):u(Object(n)).forEach((function(t){Object.defineProperty(e,t,Object.getOwnPropertyDescriptor(n,t))}))}return e}({},(0,a.configMap)({site_name:""},(0,o.mapGetters)(["viewColor"]))),mounted:function(){var e=this;r.getPrivacySetting({success:function(t){t.needAuthorization?(e.isShow=!0,e.agreementName=t.privacyContractName):e.$emit("onAgree")},fail:function(){},complete:function(){}})},methods:{handleAgree:function(){this.isShow=!1,this.$emit("onclose")},rejectAgreement:function(){this.isShow=!1,this.$emit("onReject")},privacy:function(t){e.navigateTo({url:"/pages/users/privacy/index?type="+t})}}};t.default=f}).call(this,n("543d")["default"],n("bc2e")["default"])},"9aec":function(e,t,n){"use strict";var r=n("e1fd"),c=n.n(r);c.a},c2fa:function(e,t,n){"use strict";n.r(t);var r=n("9544"),c=n.n(r);for(var i in r)["default"].indexOf(i)<0&&function(e){n.d(t,e,(function(){return r[e]}))}(i);t["default"]=c.a},e1fd:function(e,t,n){},ed0c:function(e,t,n){"use strict";var r=n("2fed"),c=n.n(r);c.a}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'components/privacyAgreementPopup/index-create-component',
    {
        'components/privacyAgreementPopup/index-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('543d')['createComponent'](__webpack_require__("7a9b"))
        })
    },
    [['components/privacyAgreementPopup/index-create-component']]
]);
