(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["components/addressWindow/index"],{"2c19":function(t,e,s){"use strict";(function(t){Object.defineProperty(e,"__esModule",{value:!0}),e.default=void 0;var a=s("6859"),n=s("26cb"),i=s("f26a"),d={props:{pagesUrl:{type:String,default:""},address:{type:Object,default:function(){return{address:!0,addressId:0}}},isLog:{type:Boolean,default:!1}},computed:(0,n.mapGetters)(["viewColor"]),data:function(){return{domain:i.HTTP_REQUEST_URL,active:0,addressList:[],is_loading:!0}},methods:{tapAddress:function(t,e){this.active=t,this.$emit("OnChangeAddress",e)},close:function(){this.$emit("changeClose"),this.$emit("changeTextareaStatus")},goAddressPages:function(){this.$emit("changeClose"),this.$emit("changeTextareaStatus"),t.navigateTo({url:this.pagesUrl})},getAddressList:function(){var t=this;(0,a.getAddressList)({page:1,limit:5}).then((function(e){for(var s=e.data.list,a=0;a<e.data.list.length;a++)s[a].address_id==t.address.addressId&&(t.active=a);t.$set(t,"addressList",s),t.is_loading=!1}))}}};e.default=d}).call(this,s("543d")["default"])},"376c":function(t,e,s){"use strict";s.r(e);var a=s("ddae"),n=s("68e5");for(var i in n)["default"].indexOf(i)<0&&function(t){s.d(e,t,(function(){return n[t]}))}(i);s("4e07");var d=s("f0c5"),r=Object(d["a"])(n["default"],a["b"],a["c"],!1,null,"5083c093",null,!1,a["a"],void 0);e["default"]=r.exports},"4e07":function(t,e,s){"use strict";var a=s("89b5"),n=s.n(a);n.a},"68e5":function(t,e,s){"use strict";s.r(e);var a=s("2c19"),n=s.n(a);for(var i in a)["default"].indexOf(i)<0&&function(t){s.d(e,t,(function(){return a[t]}))}(i);e["default"]=n.a},"89b5":function(t,e,s){},ddae:function(t,e,s){"use strict";s.d(e,"b",(function(){return a})),s.d(e,"c",(function(){return n})),s.d(e,"a",(function(){}));var a=function(){var t=this.$createElement,e=(this._self._c,!this.is_loading&&!this.addressList.length);this.$mp.data=Object.assign({},{$root:{g0:e}})},n=[]}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'components/addressWindow/index-create-component',
    {
        'components/addressWindow/index-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('543d')['createComponent'](__webpack_require__("376c"))
        })
    },
    [['components/addressWindow/index-create-component']]
]);
