(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["components/userNameSwiper/userNameSwiper"],{"18ed":function(t,e,n){},"2de8":function(t,e,n){"use strict";n.d(e,"b",(function(){return i})),n.d(e,"c",(function(){return c})),n.d(e,"a",(function(){}));var i=function(){var t=this.$createElement;this._self._c},c=[]},7748:function(t,e,n){"use strict";var i=n("18ed"),c=n.n(i);c.a},a41a:function(t,e,n){"use strict";n.r(e);var i=n("c515"),c=n.n(i);for(var a in i)["default"].indexOf(a)<0&&function(t){n.d(e,t,(function(){return i[t]}))}(a);e["default"]=c.a},c515:function(t,e,n){"use strict";(function(t){Object.defineProperty(e,"__esModule",{value:!0}),e.default=void 0;var n={data:function(){return{init:!0,distance:0,boxWidth:0,timer:null}},props:{combinationUserList:{type:Array,default:function(){}}},watch:{combinationUserList:function(){var e=this;setTimeout((function(n){var i=t.createSelectorQuery().in(e);i.select("#box").boundingClientRect((function(t){e.width=t.width,e.move()})).exec()}),1e3)}},activated:function(){this.move()},methods:{move:function(){var t=this;this.timer=setInterval((function(){t.$set(t,"distance",t.distance-t.width/t.combinationUserList.length),t.distance===-t.width&&(t.init=!1,t.distance=0,setTimeout((function(e){t.init=!0}),800))}),2500)}},destroyed:function(){clearInterval(this.timer),this.timer=null},deactivated:function(){clearInterval(this.timer),this.timer=null}};e.default=n}).call(this,n("543d")["default"])},cf8e:function(t,e,n){"use strict";n.r(e);var i=n("2de8"),c=n("a41a");for(var a in c)["default"].indexOf(a)<0&&function(t){n.d(e,t,(function(){return c[t]}))}(a);n("7748");var r=n("f0c5"),u=Object(r["a"])(c["default"],i["b"],i["c"],!1,null,"05105f40",null,!1,i["a"],void 0);e["default"]=u.exports}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'components/userNameSwiper/userNameSwiper-create-component',
    {
        'components/userNameSwiper/userNameSwiper-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('543d')['createComponent'](__webpack_require__("cf8e"))
        })
    },
    [['components/userNameSwiper/userNameSwiper-create-component']]
]);
