(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["components/verify/verify"],{"074f":function(e,t,n){"use strict";(function(e){Object.defineProperty(t,"__esModule",{value:!0}),t.default=void 0;var i={name:"Vue2Verify",props:{captchaType:{type:String,required:!0},figure:{type:Number},arith:{type:Number},mode:{type:String,default:"pop"},vSpace:{type:Number,default:5},explain:{type:String,default:"向右滑动完成验证"},imgSize:{type:Object,default:function(){return{width:"310px",height:"155px"}}},blockSize:{type:Object,default:function(){return{width:"50px",height:"50px"}}},barSize:{type:Object}},data:function(){return{clickShow:!1,verifyType:void 0,componentType:void 0,defaultImg:""}},mounted:function(){this.uuid()},methods:{uuid:function(){for(var t=[],n=0;n<36;n++)t[n]="0123456789abcdef".substr(Math.floor(16*Math.random()),1);t[14]="4",t[19]="0123456789abcdef".substr(3&t[19]|8,1),t[8]=t[13]=t[18]=t[23]="-";var i="slider-"+t.join(""),o="point-"+t.join("");e.getStorageSync("slider")||e.setStorageSync("slider",i),e.getStorageSync("point")||e.setStorageSync("point",o)},success:function(e){this.$emit("success",e)},refresh:function(){this.instance.refresh&&this.instance.refresh()},show:function(){"pop"==this.mode&&(this.clickShow=!0)},hide:function(){"pop"==this.mode&&(this.clickShow=!1)}},computed:{instance:function(){return this.$refs.instance||{}},showBox:function(){return"pop"!=this.mode||this.clickShow}},watch:{captchaType:{immediate:!0,handler:function(e){switch(e.toString()){case"blockPuzzle":this.verifyType="2",this.componentType="VerifySlide";break;case"clickWord":this.verifyType="",this.componentType="VerifyPoints";break}}}},components:{VerifySlide:function(){Promise.all([n.e("common/vendor"),n.e("components/verify/verifySlider/verifySlider")]).then(function(){return resolve(n("8161"))}.bind(null,n)).catch(n.oe)},VerifyPoint:function(){Promise.all([n.e("common/vendor"),n.e("components/verify/verifyPoint/verifyPoint")]).then(function(){return resolve(n("ccfa"))}.bind(null,n)).catch(n.oe)}}};t.default=i}).call(this,n("543d")["default"])},"496c":function(e,t,n){"use strict";n.r(t);var i=n("9fe1"),o=n("7e43");for(var r in o)["default"].indexOf(r)<0&&function(e){n.d(t,e,(function(){return o[e]}))}(r);n("e180");var c=n("f0c5"),u=Object(c["a"])(o["default"],i["b"],i["c"],!1,null,"1d4d5140",null,!1,i["a"],void 0);t["default"]=u.exports},6275:function(e,t,n){},"7e43":function(e,t,n){"use strict";n.r(t);var i=n("074f"),o=n.n(i);for(var r in i)["default"].indexOf(r)<0&&function(e){n.d(t,e,(function(){return i[e]}))}(r);t["default"]=o.a},"9fe1":function(e,t,n){"use strict";n.d(t,"b",(function(){return i})),n.d(t,"c",(function(){return o})),n.d(t,"a",(function(){}));var i=function(){var e=this,t=e.$createElement,n=(e._self._c,parseInt(e.imgSize.width));e._isMounted||(e.e0=function(t){e.clickShow=!1}),e.$mp.data=Object.assign({},{$root:{m0:n}})},o=[]},e180:function(e,t,n){"use strict";var i=n("6275"),o=n.n(i);o.a}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'components/verify/verify-create-component',
    {
        'components/verify/verify-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('543d')['createComponent'](__webpack_require__("496c"))
        })
    },
    [['components/verify/verify-create-component']]
]);
